#!/bin/bash
w=wpctl
a=@DEFAULT_AUDIO_
if [ "$q" == y ];then
    so=${a}SOURCE@;else
    so=${a}SINK@
fi
mi=microphone
vo=volume
s=set-$vo
u=set-mute
c=$($w get-$vo $so)
id=~/.config/mako/icons/
n="notify-send -h string:x-canonical-private-synchronous:sys-notify -t 2000 -i"
if [ "$m" == y ];then
    $w $u $so toggle
elif rg [MUTED] <<< $c;then
    $w $u $so 0
    um=y
elif [ $d == y ];then
    $w $s $so 5%-;else
    $w $s -l 1.0 $so 5%+
fi

v=$(wpctl get-$vo $so | cut -d\  -f2-3 | sed 's/0.00/0/' | sed 's/0\.//' | sed 's/1\./1/' | sed 's/05/5/')
if [ $q == y ];then
    if [ $v -eq 0 ];then
        ic=${id}${mi}-mute.png;else
        ic=${id}${mi}.png
    fi;else
    if [ $v -eq 0 ];then
        ic=${id}${vo}-mute.png
    elif [ $v -ge 0 ] && [ $v -le 30 ];then
        ic=${id}${vo}-low.png
    elif [ $v -ge 30 ] && [ $v -le 60 ];then
        ic=${id}${vo}-mid.png
    elif [ $v -ge 60 ] && [ $v -le 100 ];then
        ic=${id}${vo}-high.png
    fi
fi
if rg [MUTED] <<< $v;then
    if [ $q == y ];then
        $n "${id}${mi}-mute.png" "Mute";else
        $n "${id}${vo}-mute.png" "Mute"
    fi
elif ! (rg 0.00 <<< $c && [ "$d" == y ] && ! [ "$um" == y ]) && ! (rg 1.00 <<< $c && ! [ "$d" == y ] && ! [ "$m" == y ] && ! [ "$um" == y ]);then
        $n "$ic" "$v%"
fi
