[env]
WINEDEBUG = "-all"
WINEFSYNC = "1"

[player.env]
#DXVK_HUD = "fps,frametimes"
#MANGOHUD = "1"

[player.fflags]
DFIntTaskSchedulerTargetFps = 240
FStringPerformanceSendMeasurementAPISubomain = "opt-out"
DFStringHttpPointsReporterUrl = "https://opt-out.roblox.com"
DFStringAnalyticsEventStreamUrlEndpoint = "opt-out"
DFStringAltHttpReporterUrl = "https://opt-out.roblox.com"
DFStringAltTelegrafHTTPTransportUrl = "https://opt-out.roblox.com"
# Fine-tuned 24 point graphics selection
FFlagFixGraphicsQuality = "True"
# Menu Version - V1 (Comment out All for default menu)
#FFlagDisableNewIGMinDUA = "True" #False for V2
#FFlagEnableInGameMenuControls = "False"
#FFlagEnableInGameMenuModernization = "False"
#FFlagEnableMenuControlsABTest = "False"
#FFlagEnableMenuModernizationABTest = "False"
#FFlagEnableMenuModernizationABTest2 = "False"
#FFlagEnableV3MenuABTest3 = "False"

[player]
#renderer = "Vulkan" #((D3D11)) D3D11FL10 Vulkan OpenGL
#dxvk = false
launcher = "gamemoderun gamescope --force-grab-cursor --immediate-flips --adaptive-sync --"
#launcher = "gamemoderun"
gamemode = false
discord_rpc = false
#auto_kill_prefix = true

[studio]
renderer = "D3D11"
dxvk = true
#auto_kill_prefix = true
launcher = "gamemoderun"
gamemode = false

[splash]
enabled = false
style = "familiar"
