[global]
channel = "live" #live zcanary zintegration
auto_kill_prefix = true

[env]
WINEDEBUG = "-all"
WINEFSYNC = "1"

[player.env]
DXVK_HUD = "0"

[player]
renderer = "D3D11" #D3D11 D3D11FL10 Vulkan OpenGL
dxvk = true
launcher = "gamemoderun gamescope -f -W WIDTH -H HEIGHT --force-grab-cursor --" 

[studio]
renderer = "Vulkan"
launcher = "gamemoderun"
