window:
  opacity: 1
  padding:
    x: 2
    y: 2
  class:
    instance: Alacritty
    general: Alacritty
  dynamic_padding: false
  dynamic_title: true
  title: Alacritty
  gtk_theme_variant: none
  decorations: full

cursor:
  style:
    shape: Underline
    blinking: Always
  blink_interval: 750
  blink_timeout: 0
  unfocused_hollow: false

env:
  TERM: alacritty
  
scrolling:
  history: 100000
  multiplier: 10

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: false

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

enabled:
  hyperlinks: true
  command: xdg-open
  post_processing: true
  mouse:
    enabled: true
    mods: none
  
live_config_reload: true

#########################################################################################################
##########################      THEME SETTINGS        ###################################################
#########################################################################################################
#colors:
#primary:
#background: '#000000'
#foreground: '#ffffff'

########################################################################################################
##########################      FONTS       ############################################################
########################################################################################################

font:
  #JetBrains Mono Nerd Font
  normal:
    family: Hack Nerd Font Mono
    style: Regular
  bold:
    family: Hack Nerd Font Mono
    style: Bold
  italic:
    family: Hack Nerd Font Mono
    style: Italic
  bold_italic:
    family: Hack Nerd Font Mono
    style: Bold Italic
  size: 10
  # Makes terminal font smaller and weird
  offset:
    x: -1
    y: -1
  glyph_offset:
    x: 0
    y: 0
draw_bold_text_with_bright_colors: true

#########################################################################################################
##########################      KEY BINDINGS        ####################################################
########################################################################################################

key_bindings:
  - { key: F11,                           action: ToggleFullscreen }   
  - { key: Return,   mods: Control|Shift, action: SpawnNewInstance }
  - { key: C,        mods: Control|Shift, action: Copy             }
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: Key0,     mods: Control,       action: ResetFontSize    }
  - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  - { key: Plus,     mods: Control,       action: IncreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }

debug:
  # Display the time it takes to redraw each frame.
  render_timer: false

  # Keep the log file after quitting Alacritty.
  persistent_logging: false

  # Log level
  #
  # Values for `log_level`:
  #   - None
  #   - Error
  #   - Warn
  #   - Info
  #   - Debug
  #   - Trace
  log_level: Warn

  # Print all received window events.
  print_events: false
