live_config_reload = true

[window]
opacity = 1
decorations = "full"
dynamic_padding = false
dynamic_title = true
#gtk_theme_variant = "none"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 2
y = 2

[env]
TERM = "alacritty"

[shell]
program = "/usr/bin/bash"

#[enabled]
#command = "xdg-open"
#hyperlinks = true
#post_processing = true

#[mouse]

#[mouse.double_click]
#threshold = 300

#[mouse.triple_click]
#threshold = 300

[cursor]
blink_interval = 750
blink_timeout = 0
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Underline"

[scrolling]
history = 100000
multiplier = 10

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[font]
size = 10

# JetBrains Mono Nerd Font
[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[colors]
draw_bold_text_with_bright_colors = true

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false
